name: mof-search test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest]
        python-version: [ 3.8, 3.9, "3.10", 3.11 ]
    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.7"

    - name: Install dependencies
      run: |
        conda install -c conda-forge mamba=1.5.3 snakemake=7.32.4

    - name: Check out code for the build
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Test
      run: |
        make test